### PR TITLE
Added 'Cut', 'Copy', 'Paste', 'Select All' options to 'Edit' menu.

### PR DESCRIPTION
**Pull request by TimOliver**
I've added these, initially to make working with the property text fields a bit easier.
Down the line we can start adding custom functionality like duplicating Realm objects, etc.

### CODE REVIEW

**Comment by jpsim** [comment]
This works? It doesn't look hooked up to anything. Is this AppKit magic?

**Comment by TimOliver** [comment]
@jpsim Yep! Yeah, it looks like AppKit magic. The selectors those items are connected to are globally available inside the app's 'first responder' object. They're not custom definitions in Realm Browser. They switch contexts depending on what sort of UI control is currently selected.

**Comment by jpsim** [comment]
Does this also mean that copying to the clipboard via cmd-C is supported? Wasn't there a GitHub issue tracking that?

**Comment by TimOliver** [comment]
Copying text out of text fields via Cmd-C is now supported, yes.

There's issue https://github.com/realm/realm-browser-osx/issues/12 asking about not just text copy/paste editing, but also 'Excel-like' editing in being able to actually manipulate rows in the same fashion.

We've half-finished that now, but I don't think we're ready to close that issue just yet.

**Pull request merged**
