### PR TITLE
Update to Realm 3.0

### PR DESCRIPTION
**Pull request by stel**
Trying out Realm 3.0 with Stable IDs support

/cc @bdash, @jpsim

### CODE REVIEW

**Comment by bmunkholm** [comment]
I assume this is not backwards compatible with older models pre Cocoa 3.0. 
Has it been tested how it behaves when trying to open older files?

**Comment by stel** [comment]
@bmunkholm it asks user and bindings upgrade the schema as usual. I've tested it a bit but not too much. Not sure if we need to release it before 3.0 release, at least on MAS.

**Comment by bmunkholm** [comment]
We will need to make it available to the users that get the beta of ROS 2.0/cocoa 3.0/java4.0. But not make it automatically upgrade until it's officially out.
Perhaps consider if there are easy things we can do to ensure people don't automatically upgrade if they are running an older ROS.

**Comment by stel** [comment]
The current state is:
1. Browser asks to upgrade local realms' schema format
2. Browser is not able to open synced realm with older schema format and no errors reported (https://github.com/realm/realm-object-store/issues/498).

I believe we can release it here in GitHub to let users try the beta.

**Comment by jpsim** [comment]
This PR should probably be against a branch other than master. Cocoa is using `master-3.0`

**Comment by bigfish24** [comment]
Created `master-3.0` branch and publishing the artifact from this PR to Github releases for now.

**Comment by bigfish24** [comment]
@stel can we update the actual version number of the app to 3.0.0 and start automatically publishing this to the Github releases?

**Comment by stel** [comment]
Targeting this PR to `master-3.0`, will track all related changes there for now. Will update Github release and keep the same versioning as cocoa does.

**Pull request merged**
