### PR TITLE
Set linked object

### PR DESCRIPTION
**Pull request by ReDetection**
This is related to #45 
Please see note in the code, I'm not sure about one thing

### CODE REVIEW

**Comment by TimOliver** [comment]
Hi there!

Oh wow! Thank you so much for doing that! I'll review this PR (As well as see if I can diagnose that exception) as soon as I can!

**Comment by ReDetection** [comment]
Just a note: popover has transient behaviour, so if Xcode pops out, popover get dismissed. When breakpoints is disabled, everything works as expected.

**Comment by TimOliver** [comment]
Thanks a lot for this feature! I had a play with it and it's very useful!

One issue I was having with it though: when attempting to set a child object, I couldn't choose the first item in the list. It was already selected, and when I clicked on it, it simply made the element I clicked on editable. Is there a way to fix that?

Thanks!

**Comment by ReDetection** [comment]
Yea, I already had noticed that behaviour. I think it happens [here](https://github.com/realm/realm-browser-osx/blob/master/RealmBrowser/Classes/RLMInstanceTableViewController.m#L116). Why it's forced to select a row? Well, I can add a check to opt-out that auto-selection behaviour.

However, I was able to workaround that behaviour by clicking in the empty space.

**Comment by TimOliver** [comment]
Hrm, okay.

We can probably try removing that line of code. I can't think of any reason why initially selecting the first result would be necessary. :)

**Comment by ReDetection** [comment]
For the navigation just with keyboard maybe?

**Comment by TimOliver** [comment]
Yeah... that's a good point. I wonder if there's a way to selectively disable it for the popup menu then.

I can't get that workaround working. My objects have a lot of data in them, so there's no empty space to click on.

**Comment by ReDetection** [comment]
As I said, I can opt-out it. I think, NSNotFound or -1 value for `selectedIndex` and appropriate check would be ok.

**Comment by TimOliver** [comment]
Haha right. Yeah, if you can add that opt-out behavior, that would be great! :)

**Comment by ReDetection** [comment]
Here it is

**Comment by TimOliver** [comment]
Awesome! That worked perfectly for me!

Thanks again so much! :)

**Comment by ReDetection** [comment]
:sunglasses:

**Comment by TimOliver** [comment]
@ReDetection Ah right! One last thing I forgot to ask.

Could you please sign our [Contributor License Agreement](https://docs.google.com/forms/d/1bVp-Wp5nmNFz9Nx-ngTmYBVWVdwTyKj4T0WtfVm0Ozs/viewform?fbzx=4154977190905366979) so we have a legal record of your permission to use this code? The form was originally a part of the Realm Cocoa repo, but since Realm Browser is still a relatively recent repo, we haven't set it up properly here yet.

Thanks a lot for that! :)

**Comment by ReDetection** [comment]
:unamused:
You are free to use the code which I submitted to this pull request. Consider it is licensed under [WTFPL](http://www.wtfpl.net) which is compatible with yours. 
I won't sign your agreement because I won't show my mailing address.

**Comment by TimOliver** [comment]
I asked around to see if the WTFPL license was legally acceptable; turns out it is.

All good! Thanks for that!

**Pull request merged**
