### PR TITLE
Improve Main Table Scrolling Performance

### PR DESCRIPTION
**Pull request by mattbauer**
- Make parent scrollview a layer backed view
- Force table row views to be opaque
- Allow table rows to draw subviews in it's layer

### CODE REVIEW

**Comment by bigfish24** [comment]
:+1:

**Comment by timanglade** [comment]
Is this ready to merge? How do we want to review this? I believe Matt only has read rights, no commits rights so he can’t merge his own PRs. /cc @bigfish24 @jpsim @bmunkholm

**Comment by bigfish24** [comment]
@timanglade I checked out the PR and these fixes seem fine but the overall performance is still lacking. @mattbauer is looking into a bit further with a complex Realm file I sent him

**Comment by mattbauer** [comment]
@bigfish24 I found some more performance improvements in the cell view creation code. If we want more performance, we will have to change the bool cell to a textfield or Yes/No that changes to a dropdown for editing. The auto layout calculations for centering and rendering the checkbox are slowing it down. Additionally the link cell view with the badge suffers the same hit.

**Comment by bigfish24** [comment]
@mattbauer I can't get this branch to run. I get an unknown crash at launch. Any thoughts?

**Comment by bigfish24** [comment]
@mattbauer I checked out the project and I guess it might seem faster but frankly it is still completely unusable for me.

These improvements might be helping, but I did a little bit of exploration of the overall code base. Couple things:

1. Cell reuse isn't happening since the NSTableCellView subclasses implement a method: `makeWithIdentifier` which is bizarrely similar `makeViewWithIdentifier:owner:` that is what I believe you call to grab a dequeued cell. In the implementation of this custom method it is creating a new instance of the cell each time.
2. Having said the above, if I simply remove all of the code in `tableView:viewForTableColumn:row:` and simply have it return a blank reused `NSTableCellView` via:
``` objc
NSTableCellView *test = [tableView makeViewWithIdentifier:@"test" owner:self];
    
    if (!test) {
        test = [[NSTableCellView alloc] init];
        test.identifier = @"test";
    }

return test;
```
This results in the scroll performance being much better but still isn't perfect... if I scroll fast it loses fps and never has the nice deceleration.

The result of this for me, is that there is something fundamentally wrong with our UI architecture (cc @TimOliver @jpsim)

Do you have any suggestions in this regard?

**Comment by bigfish24** [comment]
@mattbauer sorry I got turned around a bit, I see what you were doing with `makeWithIdentifier:` but I am still not sure it is actually being reused... since after the initial calls to create the view once when I scroll I am seeing more calls to this versus `makeWithIdentifier:owner:` return a reused cell.

Thoughts?

**Comment by bigfish24** [comment]
@mattbauer I made a very simple implementation of a NSTableView ([download here](https://dl.dropboxusercontent.com/u/7007191/RealmBrowser.zip)) with I think cell and row reuse. It is attempting to read from that same Realm file (included in the project) to display the values for RBQSFField object... of which there are 25k entries and a fair amount of properties.

I am perplexed because it is only handling the string properties and the table view still can't scroll fast. Is this an inherent limitation?

cc @TimOliver

**Comment by mattbauer** [comment]
@bigfish24 There is a lot going on here. There is reuse going on (as verified by Instruments). There is also a lot of creation going on to as the scroll view is trying to overdraw the viewable rect. You could look into turning off the overdraw for more performance. The amount of reuse also depends on the amount of scrolling someone is doing. If someone is just scrubbing back and forth, there will be little reuse. All this logic is in NSScrollview for the most part.

**Comment by mattbauer** [comment]
@bigfish24 A quick look at your code shows that you don't have layering on for any of the views, enabling of drawing subviews into layers or setting the row views as opaque. Take a look at this talk: https://developer.apple.com/videos/play/wwdc2013-215/. AppKit views aren't layer backed by default and AppKit doesn't have some of optimizations turned on by default like UIKit.

**Comment by jpsim** [comment]
Thanks for your work on this @mattbauer and @bigfish24. At first glance, it seems like these changes improve performance with no drawbacks at all, so unless anyone thinks further improvements could be done within the context of this PR, why not merge these improvements as-is, and continue the optimization process in a new PR?

**Comment by bigfish24** [comment]
@jpsim I am fine merging this in and continuing optimizations later. @mattbauer feel free to merge and close.

**Pull request merged**
