### PR TITLE
update RealmConverter to 0.1.2 release

### PR DESCRIPTION
**Pull request by jpsim**
just updated the Podfile then ran `pod install`... not sure why it added a new build phase, so if that's concerning to either of you, let me know /cc @stel @TimOliver

### CODE REVIEW

**Comment by TimOliver** [comment]
Yeah, that's a little disconcerting. Especially when it's exactly the same as the build phase below it.

Are you running CocoaPods 1.0 yet JP? Version 1.0 prefixes all of it's build phase names with '📦' whereas the previous versions didn't.

**Comment by jpsim** [comment]
> Are you running CocoaPods 1.0 yet JP? Version 1.0 prefixes all of it's build phase names with '📦' whereas the previous versions didn't.

No, CocoaPods 1.0 has a bug preventing it from successfully integrating pods with custom private headers and header_mappings_dir on OS X (CocoaPods/CocoaPods#5313), which affects Realm. I did this with CocoaPods 0.39.0.

**Comment by jpsim** [comment]
Ah, I hadn't noticed it was the same phase as below, but with a different name... I'll remove the one added here.

**Comment by jpsim** [comment]
Done.

**Comment by TimOliver** [comment]
Ah, that would explain it. I updated to 1.0 but maybe I should roll back until these problems are fixed.

Other than that, looks good to me! :+1:

**Pull request merged**
